### ISSUE TITLE
[Q] How is GITHUB_TOKEN supposed to be passed into an action

### ISSUE THREAD

**Issue by webknjaz** [probot/actions-adapter#2]
It's not clear if using the following would do the trick:
```yaml
...
with:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Could you please document an example usage?

**Comment by swinton** [comment]
This is a good question. The way this works currently is [via an environment variable, called `GITHUB_TOKEN`](https://github.com/probot/actions-adapter/blob/d6cdf509eea15b7b4abd3e204b9c0212be7006dd/index.js#L11-L14):

https://github.com/probot/actions-adapter/blob/d6cdf509eea15b7b4abd3e204b9c0212be7006dd/index.js#L11-L14

So you would pass in the `GITHUB_TOKEN` via [`jobs.<job_id>.steps.env`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv), like so:

```yaml
...
steps:
  - name: My probot action
    uses: octocat/my-probot-action@v1  # not real, just for demonstration purposes
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I agree the documentation should be clearer here. I'll look into adding something :+1:
